# .github/workflows/windows.yml
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Windows Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/windows.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "include/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".github/workflows/windows.yml"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: configure
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}}
    - name: make
      working-directory: ${{github.workspace}}/build
      run: cmake --build .
